import type { Metadata } from "next";
import "./globals.scss";
import StoreContainer from "@/stores/StoreContainer";

export const metadata: Metadata = {
  title: {
    default: "Root Easy",
    template: "Root Easy | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreContainer>
      <html lang="pt-br">
        <body>
          {children}
        </body>
      </html>
    </StoreContainer>
  );
}
