import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/stores/ProviderStore";

export const metadata: Metadata = {
  title: {
    template: "Root Easy | %s",
    absolute: "Root Easy",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="pt-br">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
          <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.png" />
        </head>
        <body>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
